# Generated by Django 4.2.2 on 2023-08-31 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=225)),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('picture', models.ImageField(blank=True, default='item_pictures/no_picture.png', upload_to='item_pictures/')),
                ('end_time', models.DateTimeField()),
                ('date_posted', models.DateTimeField(auto_now=True)),
                ('category', models.CharField(choices=[('LAP', 'Laptop'), ('CON', 'Console'), ('GAD', 'Gadget'), ('GAM', 'Game'), ('TEL', 'Tv'), ('JWL', 'Jewelry'), ('ART', 'Art and collectibles'), ('COL', 'Collectibles and memorabilia'), ('FAS', 'Fashion & Accessories'), ('BKS', 'Books'), ('HOM', 'Home or Garden'), ('TOY', 'Toys and hobbies')], max_length=3)),
                ('is_sold', models.BooleanField(default=False)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
