# Generated by Django 4.2.2 on 2023-09-02 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_delete_item', 'can delete item')]},
        ),
    ]
