# Generated by Django 4.2.2 on 2023-09-03 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0002_alter_item_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='item',
            options={'permissions': [('can_delete_item', 'can delete item'), ('can_change_item', 'Can change item')]},
        ),
    ]
