# Generated by Django 4.2.2 on 2023-09-04 18:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0003_alter_item_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='is_sold',
        ),
    ]
