# Generated by Django 4.2.2 on 2023-09-04 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0004_remove_item_is_sold'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='item',
            name='winner_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
