# Generated by Django 4.2.2 on 2023-09-04 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0006_alter_item_winner_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='winner_id',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
