# Generated by Django 4.2.2 on 2023-09-04 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='sold',
            field=models.BooleanField(default=False),
        ),
    ]
