# Generated by Django 4.2.2 on 2023-09-04 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bids', '0002_bid_sold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bid',
            name='sold',
        ),
    ]
